version: '3.8'

services:

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ancestra_realm
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql:/ancestra
      - ./servers:/ancestra/servers
    networks:
      - mysql

  adminer:
    image: adminer
    ports:
      - 9090:8080
    networks:
      - mysql

  static:
    image: 'bitnami/apache:2.4'
    ports:
      - 8081:8080
    volumes:
      - ./www:/app

  realm:
    image: ancestra/realm:latest
    ports:
      - 444:444
    configs:
      - source: realm_conf
        target: /ancestra/Realm_Config.txt
    networks:
      game:
      realm:
      mysql: ~

  game:
    image: ancestra/game:latest
    ports:
      - 5555:5555
    configs:
      - source: server_game_conf
        target: /ancestra/Game_Config.txt
    networks:
      game:
      realm:
      mysql: ~

configs:
  realm_conf:
    file: ./realm/Realm_Config.txt
  server_game_conf:
    file: ./servers/game/Game_Config.txt

volumes:
    mysql_data:

networks:
    traefik_reverse_proxy:
        external: true
    mysql: ~
    game: ~
    realm: ~